// File generated by FlutterFire CLI (templated).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderWebApiKeyHere',
    appId: '1:1234567890:web:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'pulse-chat-799d9',
    authDomain: 'pulse-chat-799d9.firebaseapp.com',
    storageBucket: 'pulse-chat-799d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBktzcq-93aRZW5UfcO6dET-o4jL6H0M',
    appId: '1:1031485890057:android:651868b071ca44546ae2d8',
    messagingSenderId: '1031485890057',
    projectId: 'pulse-chat-799d9',
    databaseURL: 'https://pulse-chat-799d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulse-chat-799d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjj1HQjP8EZkqP6w8IYih5NHhaZxADOXQ',
    appId: '1:1031485890057:ios:a0ba9ff8b2042eb06ae2d8',
    messagingSenderId: '1031485890057',
    projectId: 'pulse-chat-799d9',
    databaseURL: 'https://pulse-chat-799d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulse-chat-799d9.firebasestorage.app',
    iosClientId: '1031485890057-s6tairqirm3v8scf4ee6rrsp11evke18.apps.googleusercontent.com',
    iosBundleId: 'com.irawnewton.pulseChat',
  );

}